# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'PTGToBidDemo' do
  
  post_install do |installer|
        installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
        end
      end
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ToBid-iOS','~> 4.5.30'
  pod 'PTGAdFramework','2.2.95'
  pod 'PTGToBidAdapter','2.2.80.0'
  pod 'YYCategories'
  pod 'CocoaDebug'
  pod 'Masonry'

  # Pods for PTGToBidDemo

end
